### ISSUE TITLE
[ERROR] Error : 429

### ISSUE THREAD

**Issue by GreenAA** [RetrO-M/Hawker#1]
thanks

i get error 

[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bsite%253Adoxbin.org%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGOip0roGIjDgXDCL0-51xWyn2O7m_TNodKb8Fq0pOIU6yHL02iTdfdqrOTJEoFrsHTGyKCuFIogyAXJaAUM 
[WAIT] Searching for Gilad Sgabtai
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bfiletype%253Apdf%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGOmp0roGIjBVRyYjS-IQrmJ-ELtl8k8D2bSB5L5A6nXdP0wjUHiSB8JC7tOxYNhwp_3kA7bI3-8yAXJaAUM    
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bfiletype%253Axlsx%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGOqp0roGIjD4kahquyNvk87w21hf_p1plBDGJGlQqpecgDUMFh1h3UNFS-15jYiQ4BEipT11i9wyAXJaAUM   
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bfiletype%253Adocx%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGOqp0roGIjCU95cCRfvYyQ3kpBr2ePaxvLAt550OT4Oe75UHO036Q4kerLv6sVu85IWlPgaAyFgyAXJaAUM   
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bfiletype%253Atxt%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGOup0roGIjBREhTMc_dc5psPUDwwAmZ6LNHMHfAVJo8_UMxKdkwrYMrf0_V4u4-YVi8eVcmmVl0yAXJaAUM    
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bfiletype%253Axls%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGOyp0roGIjBT0w7ozE91AhtS5xPoNJqeAhStsaUM8wksuL61dWM4OpJ6GDuEapPwfuHE7AA_FSQyAXJaAUM    
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bfiletype%253Adoc%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGO2p0roGIjDDo5jtEcjc5xBNJADz2EDX_R99QTuMFuJjHSgacfT_TlNYSTpzo10tS1GZ3w9J0iwyAXJaAUM    
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bfiletype%253Appt%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGO6p0roGIjBu6LrirkTZ07JxTSF92fTdf4v6PcLYiNH0aAP3gYjlO-INnVH3h1-OTHaat1J2CzAyAXJaAUM    
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bfiletype%253Arft%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGO-p0roGIjDiDZKU_Eu9TOwlXDRvpfUe8F237_XZJ7g4zkA1X3szr6rbYtI6Y69_2Z_BHHDNkFQyAXJaAUM    
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bfiletype%253Aodt%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGPCp0roGIjB2hQqMmplOmSyHBmdOh8ARs0U4Kr-L4h780SGLi6Yw-jVL1MtrjDHCocvflF_TJx4yAXJaAUM    
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bfiletype%253Acsv%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGPCp0roGIjAsK8sXQ10122hsEXp7VcA0uHdFVEqNhMGgHfmNr-BCmGh1OR7hMSEN69-D1vRnecgyAXJaAUM    
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bsite%253Ainstagram.com%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGPGp0roGIjBq0mZOMYUDlKq2VxLt__6e-anzXoHmogHcuTcmT_3D9mVprYeshPdC-Q5NcV8oPfsyAXJaAUM
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bsite%253Ax.com%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGPKp0roGIjDLjozTg14ddk8WpHQyT98s3BiHKAP1sgCrKie9BB3XJJDjv55PHfyFtgAjKDN1TGsyAXJaAUM      
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bsite%253Ayoutube.com%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGPOp0roGIjCo7F2FCygKu6839ca_5nawCNhu0Q0iSnFwzTDgM_34QiqAdZnMYQGJxp4kDj19p0UyAXJaAUM
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bsite%253Afacebook.com%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGPSp0roGIjC0tpG2AEvADoI52xVqQCcGXYicPXUKjuEBwyNeJz3yhiB6SUKv9SaHcs6EWj1jL5IyAXJaAUM
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bsite%253Apagesjaunes.fr%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGPWp0roGIjAI8YWCrDhY7_OBLDnxpWCuO8kbr-aY0gDf416oQ1FR1SGhlXAdDtfQxhBtm_LAlI0yAXJaAUM
[ERROR] Error : 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DGilad%2BSgabtai%2Bsite%253Awhitepages.com%26hl%3Den%26num%3D10&hl=en&q=EgSpluPkGPap0roGIjDusLEwB3tp7clItXOf0eil__hECz4GYt18Rp62E4413a5BweXk1Dy-AFkzTUJ4XVwyAXJaAUM

**Comment by RetrO-M** [comment]
Hi @GreenAA,

This error 429 means too many requests were sent in a short amount of time. Try spacing out the requests or reducing their frequency. You can also use a VPN to change the IP address and avoid getting blocked, while respecting the service's rules 🤝

Take care of yourself and see you soon if you need help you ask me I will try to help you as much as possible 😁

**Comment by GreenAA** [comment]
thanks bro .. i have vpn  active . i try .. thanks for app

**Comment by RetrO-M** [comment]
Glad I could help! If you run into any other issues, feel free to reach out. Good luck with everything 💻

**Comment by GreenAA** [comment]
wow perfect app . thank now working
